### ISSUE TITLE
Airtable

### ISSUE THREAD

**Issue by bshyong** [Choxue/cxleague-rails#1]
@dengel29 

Did you mean to have games and other models inherit from ApplicationRecord instead of Airrecord::Table?

https://github.com/sirupsen/airrecord#airrecord

`class Game < Airrecord::Table`

You do not need to use the model generators if you are simply creating abstract models for use with the Airrecord gem

**Comment by dengel29** [comment]
Yeah I mention this in the README as an error I made with the initial setup of the project. I do intend to just have them inheriting from Airrecord, plan to undo the scaffolding created by rails g model tomorrow.

**Comment by dengel29** [comment]
Got rid of the files generated by `rails g model MODEL` and fixed the inheritance for all models
